config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  resources :users, except: [:new]

  root "posts#index"
  get 'signup', to: 'users#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :content, presence: true 
    #validates :user_id, presence: true

    #before_save { self.email = email.downcase }
end

app/models/user.rb
class User < ActiveRecord::Base 
    has_many :posts
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+/i
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
    validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
    validates :password_digest, presence: true, length: { minimum: 6, maximum: 25 }
    
    before_save { self.email = email.downcase }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :comment))
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :find_post, only:[:show, :update, :edit, :destroy]

    def index 
        @posts = Post.all.order("created_at DESC")
    end

    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        @post.user = User.first
        if @post.save
            flash[:notice] = "Post was successfully created."
            redirect_to @post
        else
            render 'new'
        end
    end

    def show
    end

    def update
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end

    def edit
    end

    def destroy
        @post.destroy

        redirect_to posts_path
    end
    
    private

    def post_params
        params.require(:post).permit(:title, :content)
    end

    def find_post
        @post = Post.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params) 
        if @user.save
            flash[:success] = "Welcome to the Travel blog #{@user.username}"
            redirect_to posts_path
        else
            render 'new'
        end
    end

    def destroy
        @user.destroy
        redirect_to posts_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
    <article class="media">
        <div class="media-content">
            <div class="content">
                <p>
                    <strong><%= comment.name %>: </strong>
                    <%= comment.comment %>
                </p>
            </div>        
        </div>

        <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: "Are you sure want to delete your comment?" } %>
    </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
    <div class="field">
        <div class="control">
            <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <div class="field">
        <div class="control">
            <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adventure Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<section class="hero is-medium is-primary is-danger">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to 'Home', root_path, class: "navbar-item" %>

          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to "Create New Post", new_post_path, class:"navbar-item" %>
            
            <%= link_to "Account Sign-Up", signup_path, class:"navbar-item" %>
            
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <%= yield :page_title %>
      </p>
      <p class="subtitle">
        Travel Adventures
      </p>
    </div>
  </div>
</section>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
    <%= simple_form_for @post do |f| %>
    <div class= "field">
        <div class="control">
            <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <div class= "field">
        <div class="control">
        <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>
    <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title, "Index" %>


<section class="section">
   <div class="container">
        <% @posts.each do |post|%>
            <div class="card">
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <p class="title is-4"> <%= link_to post.title, post %></p>
                        </div>
                    </div>
                    <div class="content">
                        <%= post.content %>
                        <small>Created by: <%= post.user.username if post.user %>,
                            <%= time_ago_in_words(post.created_at) %> ago, last updated: <%= time_ago_in_words(post.updated_at) %> ago
                        </small>
                    </div>
                </div>
            </div>
        <% end %>
   </div> 
</section>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a New Post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
    <div class="container">
        <nav class="level">
            <!----Left side---->
            <div class="level-left">
                <p class="level-item">
                    <strong>Actions</strong>
                </p>
            </div>

            <!-----Right side ---->
            <div class="level-right">
                <p class="level-item">
                    <%= link_to "Edit", edit_post_path(@post), class: "button" %>
                </p>
                <p class="level-item">
                    <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post? "}, class: "button is-link" %>
                </p>
            </div>
        </nav>
        <hr />
        
        <div class="content">
            <%= @post.content %>
        </div>    
    </div>
</section>

<section class="section comments">
    <div class="container">
        <h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
        <%= render @post.comments %>
        <div class="comment-form">
            <hr />
            <h3 class="subtitle is-3">Leave a reply</h3>
            <%= render 'comments/form' %>
        </div>
    </div>
</section>

app/views/users/_form.html.erb
<div class="section">
    <%= simple_form_for @user do |f| %>
    <div class= "field">
        <div class="control">
            <%= f.input :username, input_html: { class: 'input', placeholder: 'Enter a Username' }, wrapper: false, label_html: { class: 'label'} %>
        </div>
    </div>
    <div class= "field">
        <div class="control">
        <%= f.input :email, input_html: { class: 'input', placeholder: 'Enter an Email' }, wrapper: false, label_html: { class: 'label' } %>
        </div>
    </div>
    <div class= "field">
        <div class="control">
        <%= f.input :password, input_html: { class: 'input', placeholder: 'Enter a Password' }, wrapper: false, label_html: { class: 'label' } %>
        </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>
    <% end %>
    <div class="level-item">
        <%= link_to "Cancel request and Return to Posts", posts_path %>
    </div>
</div>

app/views/users/new.html.erb
<% content_for :page_title, "User Sign-Up" %>

<%= render 'form' %>